Try to repro #1907
By narrowing down the test and introducing some looping (maybe too much
looping? i dunno!) I can usually eventually reproduce this issue
eventually by running `doit.sh`.

For example:

```
+ go test ./configmap/... -run TestInformedWatcher -count=1
--- FAIL: TestInformedWatcher (0.00s)
    --- FAIL: TestInformedWatcher/AGAIN-175 (0.00s)
        informed_watcher_test.go:94: foo1.count = 0, want 1
        informed_watcher_test.go:94: foo2.count = 0, want 1
        informed_watcher_test.go:94: bar.count = 0, want 1
FAIL
```